### PR TITLE
Add support for animation encoding

### PR DESCRIPTION
**Pull request by rohansingh**
Add a wrapper around `webpmux` to encode animations.

### CODE REVIEW

**Comment by rohansingh** [comment]
Looks like this would break support for libwebp < 0.5. Seeing as the current version is 1.1.0, that seems fine to me. Thoughts?

**Comment by rohansingh** [comment]
@phanirithvij Sure. Thanks for pointing out that project, I'd be happy to switch to an actively-maintained project.

Honestly I haven't the faintest clue how Windows works though.

**Comment by harukasan** [comment]
Sorry for the  late reply. At this time, I'm not considering to support animation features.

**Comment by rohansingh** [comment]
Understood. We have orphaned our own fork and are maintaining it here: https://github.com/tidbyt/go-libwebp

**Pull request closed without merging**
